# Generated by Django 3.1.3 on 2020-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('name', models.CharField(max_length=256, verbose_name='folder_task_name')),
            ],
            options={
                'verbose_name': 'Папка заданий',
                'verbose_name_plural': 'Папки заданий',
                'permissions': (('menu_view_folder_task', 'Папки заданий - в Меню'),),
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('name', models.CharField(max_length=256, verbose_name='sanction_name')),
            ],
            options={
                'verbose_name': 'Санкция',
                'verbose_name_plural': 'Санкции',
                'permissions': (('menu_view_sanction', 'Санкции - в Меню'),),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('name', models.CharField(max_length=256, verbose_name='task_name')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'permissions': (('menu_view_task', 'Задания - в Меню'),),
            },
        ),
    ]
