# Generated by Django 3.1.3 on 2020-11-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanction',
            options={'permissions': (('menu_view_sanction', 'Санкции - в Меню'), ('menu_view_sanction_interception', 'Санкции - перехвата сообщений - в Меню'), ('menu_view_sanction_information', 'Санкции - служеюная информация - в Меню')), 'verbose_name': 'Санкция', 'verbose_name_plural': 'Санкции'},
        ),
    ]
