# Generated by Django 3.1.3 on 2020-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_auto_20201119_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('name', models.CharField(max_length=256, verbose_name='person_identifiers_name')),
            ],
            options={
                'verbose_name': 'Идентификатор абонента',
                'verbose_name_plural': 'Идентификаторы абонентов',
                'permissions': (('menu_view_person_identifiers', 'Идентификаторы абонентов - в Меню'),),
            },
        ),
    ]
