# Generated by Django 3.1.3 on 2020-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('codename', models.CharField(max_length=32)),
                ('link', models.CharField(help_text='Вводится без указания хоста', max_length=512, verbose_name='Ссылка')),
                ('state', models.BooleanField(default=True, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
