# Generated by Django 3.1.3 on 2021-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('link', models.CharField(db_index=True, max_length=512, verbose_name='Ссылка')),
                ('class_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя класса')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Номер запроса')),
                ('name', models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователя',
            },
        ),
    ]
