# Generated by Django 3.1.3 on 2021-01-20 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('kind', models.CharField(choices=[('simple', 'Простой'), ('foreign', 'Внешний')], default='simple', max_length=10, verbose_name='Тип запроса')),
                ('class_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя класса')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Номер запроса')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В работе'), ('complete', 'Завершён'), ('error', 'Ошибка')], default='new', max_length=16, verbose_name='Статус')),
                ('note', models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='Заметка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователя',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('before', models.TextField(blank=True, null=True, verbose_name='До изменения')),
                ('after', models.TextField(blank=True, null=True, verbose_name='После изменения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.userrequest', verbose_name='Запрос пользователя')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
            },
        ),
    ]
