# Generated by Django 3.1.3 on 2020-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Органы ОРМ и надзора',
                'verbose_name_plural': 'Органы ОРМ и надзора',
                'permissions': (('menu_view_organization', 'Органы ОРМ и надзора - в Меню'),),
            },
        ),
    ]
