# Generated by Django 3.1.3 on 2020-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20201119_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('orm', 'ORG_ORM'), ('supervision', 'ORG_SUPERVISION')], default=1, max_length=16, verbose_name='organization_kind'),
            preserve_default=False,
        ),
    ]
