# Generated by Django 3.1.3 on 2020-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_organization_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='organization_name'),
        ),
    ]
