# Generated by Django 3.1.3 on 2020-11-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={'permissions': (('menu_view_account', 'Учётные записи - в Меню'),), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
