# Generated by Django 3.1.3 on 2020-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20201118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last_name'),
        ),
    ]
