# Generated by Django 3.1.3 on 2020-11-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20201119_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={'permissions': (('menu_view_account', 'Учётные записи - в Меню'), ('menu_view_change_password', 'Смена пароля - в Меню')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
